# THỐNG KÊ MÁY TÍNH VÀ ỨNG DỤNG (ĐTTX)

**Khoa Công nghệ Thông tin - ĐH Khoa học Tự nhiên TP. HCM ([fit@hcmus](https://www.fit.hcmus.edu.vn/))**

*Giảng viên: Vũ Quốc Hoàng (vqhoang@fit.hcmus.edu.vn)*

# BÀI 4 - XỬ LÝ BẢNG DỮ LIỆU VỚI PANDAS (Phần 2)

**Nội dung**

* [Đọc bảng số liệu từ tập tin vào `DataFrame`](#doc_file)
* [Xử lý dữ liệu bị thiếu](#missing_data)
* [Nhóm dữ liệu với `groupby`](#nhom_du_lieu)
* [Bảng tổng hợp](#bang_tong_hop)

**Tài liệu tham khảo**

* Chương 16, 20, 21 [Python Data Science Handbook (Jake VanderPlas)](https://www.amazon.com/Python-Data-Science-Handbook-Essential-dp-1098121228/dp/1098121228/)

In [1]:
import numpy as np
import pandas as pd

## <a name="doc_file"/>Đọc bảng số liệu từ tập tin vào `DataFrame`

Dữ liệu [`Iris Data Set`](https://archive.ics.uci.edu/ml/datasets/Iris).

Ta đọc dữ liệu trong file CSV vào `DataFrame` bằng hàm [`pd.read_csv`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv)

In [2]:
iris_names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]
iris = pd.read_csv("iris.data", names=iris_names)
iris

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
iris.head(5)

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
iris.tail(5)

     sepal_length  sepal_width  petal_length  petal_width           class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [5]:
iris.iloc[-5:,:]

     sepal_length  sepal_width  petal_length  petal_width           class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [6]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='object')

In [7]:
iris.index

RangeIndex(start=0, stop=150, step=1)

In [8]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   class         150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [9]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [10]:
iris["class"].value_counts()

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [11]:
iris.loc[iris["sepal_length"] < 5, :]

     sepal_length  sepal_width  petal_length  petal_width            class
1             4.9          3.0           1.4          0.2      Iris-setosa
2             4.7          3.2           1.3          0.2      Iris-setosa
3             4.6          3.1           1.5          0.2      Iris-setosa
6             4.6          3.4           1.4          0.3      Iris-setosa
8             4.4          2.9           1.4          0.2      Iris-setosa
9             4.9          3.1           1.5          0.1      Iris-setosa
11            4.8          3.4           1.6          0.2      Iris-setosa
12            4.8          3.0           1.4          0.1      Iris-setosa
13            4.3          3.0           1.1          0.1      Iris-setosa
22            4.6          3.6           1.0          0.2      Iris-setosa
24            4.8          3.4           1.9          0.2      Iris-setosa
29            4.7          3.2           1.6          0.2      Iris-setosa
30            4.8          3.1           1.6          0.2      Iris-setosa
34            4.9          3.1           1.5          0.1      Iris-setosa
37            4.9          3.1           1.5          0.1      Iris-setosa
38            4.4          3.0           1.3          0.2      Iris-setosa
41            4.5          2.3           1.3          0.3      Iris-setosa
42            4.4          3.2           1.3          0.2      Iris-setosa
45            4.8          3.0           1.4          0.3      Iris-setosa
47            4.6          3.2           1.4          0.2      Iris-setosa
57            4.9          2.4           3.3          1.0  Iris-versicolor
106           4.9          2.5           4.5          1.7   Iris-virginica

In [12]:
iris.loc[(iris.sepal_length < 5) & (iris.sepal_width < 3), :]

     sepal_length  sepal_width  petal_length  petal_width            class
8             4.4          2.9           1.4          0.2      Iris-setosa
41            4.5          2.3           1.3          0.3      Iris-setosa
57            4.9          2.4           3.3          1.0  Iris-versicolor
106           4.9          2.5           4.5          1.7   Iris-virginica

Ta cũng có thể trích riêng các cột (nhưng thường không cần thiết).

In [13]:
iris_classes = iris["class"]
iris_classes

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: class, Length: 150, dtype: object

Ta có thể đọc dữ liệu từ các định dạng khác với các hàm `pd.read_*` và ghi dữ liệu với các hàm `pd.to_*`. Chẳng hạn đọc, ghi dữ liệu từ tập tin Excel bằng hàm `pd.read_excel`, `pd.to_excel`.

In [14]:
# chạy lệnh sau để cài thư viện openpyxl (nếu chưa cài)
# %pip install openpyxl

In [15]:
iris.to_excel("iris_data.xlsx", index=False)

In [16]:
pd.read_excel("iris_data.xlsx")

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

**Bài tập**

Trên bảng dữ liệu `iris`.
1. Trích bảng con các dòng mà sepal_width lớn hơn 3.5.
1. Trích bảng con các dòng mà sepal_width lớn hơn 3.5 hoặc petal_width lớn hơn 1.8.
1. Tính trung bình cột sepal_width.
1. Trích bảng con các dòng mà sepal_width lớn hơn trung bình của các sepal_width.
1. Tính min, max, range (max - min), mean từng cột.
1. Tìm dòng đạt min tại sepal_length.
1. Tìm dòng đạt max tại sepal_width.

In [17]:
# TODO

**Bài tập**

Trên bảng dữ liệu `iris`.
1. Đếm số lượng hoa Iris giống virginica có sepal width lớn hơn 3.
1. Cho biết min, max, mean của sepal width của các hoa Iris giống virginica.
1. Cho biết có cây hoa Iris giống virginica nào có petal length nhỏ hơn 4 hay không.

In [18]:
# TODO

**Bài tập**

Trên bảng dữ liệu `iris`.
1. Thêm một cột mới `sepal_length_inch` là sepal length nhưng tính theo đơn vị inch.
1. Thêm một cột mới `all_cm` là tích của các cột cm.
1. Tạo bảng dữ liệu mới `iris_centered` với dữ liệu đã được canh giữa (centering).
1. Lưu bảng dữ liệu mới `iris_centered` vào tập tin Excel.

In [19]:
# TODO

## <a name="missing_data"/>Xử lý dữ liệu bị thiếu

pandas dùng các giá trị `None` hay `NaN` hay `NA` để đánh dấu **dữ liệu bị thiếu** (missing data). Trong đó, nên dùng nhất là `np.NaN`.

In [20]:
pd.Series([1, None, 2, pd.NA, 3, np.NaN])

0       1
1    None
2       2
3    <NA>
4       3
5     NaN
dtype: object

In [21]:
sr1 = pd.Series([1, 2, 3], index=list("abc"))
sr2 = pd.Series([4, 5, 6], index=list("bad"))
print(sr1)
print(sr2)
print(sr1 * sr2)

a    1
b    2
c    3
dtype: int64
b    4
a    5
d    6
dtype: int64
a    5.0
b    8.0
c    NaN
d    NaN
dtype: float64

Các thao tác trên bảng dữ liệu thường bỏ qua các giá trị NA (tương tự như cách Excel bỏ qua các ô trống).

In [22]:
data = pd.DataFrame([[1, 2, np.NaN],
                     [3, 4, np.NaN],
                     [5, np.NaN, np.NaN]])
data

   0    1   2
0  1  2.0 NaN
1  3  4.0 NaN
2  5  NaN NaN

In [23]:
data.mean()

0    3.0
1    3.0
2    NaN
dtype: float64

In [24]:
data.mean(skipna=False)

0    3.0
1    NaN
2    NaN
dtype: float64

Ta dùng phương thức hàm `isna` (`isnull`) và `notna` (`notnull`) để kiểm tra giá trị nào là NA trong `Series` hay `DataFrame`.

In [25]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [26]:
data.isna()

0    False
1     True
2    False
3     True
dtype: bool

In [27]:
data.notna()

0     True
1    False
2     True
3    False
dtype: bool

In [28]:
data[data.notna()]

0        1
2    hello
dtype: object

Ta dùng phương thức `dropna` để xóa NA (trong `Series`) hoặc dòng/cột chứa NA (trong `DataFrame`).

In [29]:
print(data)
print(data.dropna())

0        1
1      NaN
2    hello
3     None
dtype: object
0        1
2    hello
dtype: object

In [30]:
df = pd.DataFrame([[1, np.nan, 2],
                   [2, 3, 5],
                   [np.nan, 4, 6]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [31]:
df.dropna() # xóa tất cả các dòng chứa NA

     0    1  2
1  2.0  3.0  5

In [32]:
df.dropna(axis=1) # xóa tất cả các cột chứa NA

   2
0  2
1  5
2  6

Ta dùng phương thức `fillna` để điền giá trị vào dữ liệu bị thiếu (thay NA bằng giá trị nào đó).

In [33]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [34]:
data.fillna(0) # thay NA bằng 0

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [35]:
data.fillna(method='ffill') # thay NA bằng giá trị trước đó

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [36]:
data.fillna(method='bfill') # thay NA bằng giá trị sau đó

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [37]:
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [38]:
df.fillna(method='ffill', axis=1) # thay NA bằng giá trị trước đó trên cùng dòng

     0    1    2
0  1.0  1.0  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0

## <a name="nhom_du_lieu"/>Nhóm dữ liệu với `groupby`

Ta đã biết cách tổng hợp (aggregation) hay thu (reduction) dữ liệu trong pandas (và NumPy) với các hàm `sum`, `prod`, `mean`, `min`, `max` (hay `count`, `first`, `last`, `median`, `std`, `var`, `mad`).

In [39]:
ser = pd.Series(np.random.randint(0, 10, 5))
ser

0    5
1    3
2    1
3    4
4    9
dtype: int32

In [40]:
print(ser.sum())
print(ser.max())

22
9

In [41]:
mask = ser > 5
mask

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [42]:
print(mask.sum())
print(mask.count())

1
5

In [43]:
df = pd.DataFrame({c: np.random.randint(0, 10, 5) for c in "ABC"})
df

   A  B  C
0  5  9  0
1  5  0  9
2  3  8  0
3  8  4  7
4  9  7  5

In [44]:
df.sum()

A    30
B    28
C    21
dtype: int64

In [45]:
df.sum(axis=1)

0    14
1    14
2    11
3    19
4    21
dtype: int64

Trước khi tổng hợp dữ liệu ta có thể thực hiện việc **tách nhóm** (split) với  `groupby`.

In [46]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'], 'data': range(1, 7)})
df

  key  data
0   A     1
1   B     2
2   C     3
3   A     4
4   B     5
5   C     6

In [47]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'], 'data': range(1, 7)})

for val, df in df.groupby("key"):
    print(f"Tách nhóm theo giá trị {val} trên key được DataFrame:")
    print(df)
    print(f"Có kết quả thu trên data là {df['data'].sum()}")
    print()

Tách nhóm theo giá trị A trên key được DataFrame:
  key  data
0   A     1
3   A     4
Có kết quả thu trên data là 5

Tách nhóm theo giá trị B trên key được DataFrame:
  key  data
1   B     2
4   B     5
Có kết quả thu trên data là 7

Tách nhóm theo giá trị C trên key được DataFrame:
  key  data
2   C     3
5   C     6
Có kết quả thu trên data là 9

Sau đó ta có thể thực hiện việc tổng hợp trên từng nhóm và **kết hợp** (combine) kết quả lại trong một `Series` hay `DataFrame`.

In [48]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'], 'data': range(1, 7)})

df.groupby("key").sum()

     data
key
A       5
B       7
C       9

Việc tách nhóm có thể được thực hiện trên giá trị của nhiều cột.

In [49]:
df = pd.DataFrame({'key1': ['A', 'A', 'A', 'B', 'B', 'B'],
                   'key2': ['a', 'a', 'b', 'a', 'b', 'b'],
                   'data1': range(1, 7),
                   'data2': range(11, 17)})
df

  key1 key2  data1  data2
0    A    a      1     11
1    A    a      2     12
2    A    b      3     13
3    B    a      4     14
4    B    b      5     15
5    B    b      6     16

In [50]:
df.groupby("key1").sum()

     key2  data1  data2
key1
A     aab      6     36
B     abb     15     45

In [51]:
df.groupby("key2").sum()

     key1  data1  data2
key2
a     AAB      7     37
b     ABB     14     44

In [52]:
df.groupby(["key1", "key2"]).sum()

           data1  data2
key1 key2
A    a         3     23
     b         3     13
B    a         4     14
     b        11     31

Việc tách nhóm cũng có thể dựa vào mảng các nhãn cho các dòng trong `DataFrame`.

In [53]:
df

  key1 key2  data1  data2
0    A    a      1     11
1    A    a      2     12
2    A    b      3     13
3    B    a      4     14
4    B    b      5     15
5    B    b      6     16

In [54]:
row_labels = [i % 2 for i in range(df.shape[0])]
row_labels

[0, 1, 0, 1, 0, 1]

In [55]:
df.groupby(row_labels).sum()

  key1 key2  data1  data2
0  AAB  abb      9     39
1  ABB  aab     12     42

Với `groupby` ta cũng có thể thay công việc thu trong "tách nhóm - thu - kết hợp" bằng **lọc** (filter), **biến đổi** (transform), **áp dụng** (apply).

In [56]:
df

  key1 key2  data1  data2
0    A    a      1     11
1    A    a      2     12
2    A    b      3     13
3    B    a      4     14
4    B    b      5     15
5    B    b      6     16

In [57]:
df.groupby("key1").sum()   # thu với các hàm tổng hợp

     key2  data1  data2
key1
A     aab      6     36
B     abb     15     45

In [58]:
df.groupby("key1").aggregate(['max', np.max, max]) # thu với hàm aggregate

     key2         data1         data2
      max max max   max max max   max max max
key1
A       b   b   b     3   3   3    13  13  13
B       b   b   b     6   6   6    16  16  16

In [59]:
df.drop("key2", axis=1).groupby("key1").aggregate(['max', np.max, max])

     data1         data2
       max max max   max max max
key1
A        3   3   3    13  13  13
B        6   6   6    16  16  16

In [60]:
df.groupby('key1').aggregate({'data1': 'min', 'data2': 'max'})

      data1  data2
key1
A         1     13
B         4     16

In [61]:
df

  key1 key2  data1  data2
0    A    a      1     11
1    A    a      2     12
2    A    b      3     13
3    B    a      4     14
4    B    b      5     15
5    B    b      6     16

In [62]:
df.groupby("key1").sum()

     key2  data1  data2
key1
A     aab      6     36
B     abb     15     45

In [63]:
df.groupby("key1").filter(lambda gr: gr["data1"].sum() > 10) # lọc với hàm filter

  key1 key2  data1  data2
3    B    a      4     14
4    B    b      5     15
5    B    b      6     16

In [64]:
df.drop("key2", axis=1).groupby("key1").transform(lambda gr: gr - gr.iloc[0])

   data1  data2
0      0      0
1      1      1
2      2      2
3      0      0
4      1      1
5      2      2

In [65]:
df.groupby("key1").apply(lambda gr: True if gr['data1'].sum() > 10 else False) # áp dụng với hàm apply

key1
A    False
B     True
dtype: bool

**Bài tập**

1. Nạp lại bảng dữ liệu `Iris Data Set` (https://archive.ics.uci.edu/ml/datasets/iris)

1. Kiểm tra để biết bảng dữ liệu này không có NA

1. Tính trung bình (mean) và độ lệch chuẩn (std) của từng đặc trưng (sepal length, sepal width, petal length, petal width) trên tất cả các hoa (tất cả các dòng dữ liệu)

1. Tính trung bình và độ lệch chuẩn của từng đặc trưng trên từng nhóm hoa phân theo nhãn lớp (class), từ đó đưa ra nhận xét

In [66]:
# TODO

## <a name="bang_tong_hop"/>Bảng tổng hợp

Cũng như `groupby`, pandas hỗ trợ việc tách nhóm và tổng hợp dữ liệu tiện lợi với **bảng tổng hợp** (pivot table). Khác với `groupby`, các bảng tổng hợp được bố trí theo 2 chiều (thay vì 1 chiều).

In [67]:
df = pd.DataFrame({'key1': ['A', 'A', 'A', 'B', 'B', 'B'],
                   'key2': ['a', 'a', 'b', 'a', 'b', 'b'],
                   'data1': range(1, 7),
                   'data2': range(11, 17)})
df

  key1 key2  data1  data2
0    A    a      1     11
1    A    a      2     12
2    A    b      3     13
3    B    a      4     14
4    B    b      5     15
5    B    b      6     16

In [68]:
df.groupby(["key1", "key2"]).sum()

           data1  data2
key1 key2
A    a         3     23
     b         3     13
B    a         4     14
     b        11     31

In [69]:
df.groupby(["key1", "key2"]).sum().unstack()

     data1     data2
key2     a   b     a   b
key1
A        3   3    23  13
B        4  11    14  31

In [70]:
df.groupby(["key1", "key2"])["data1"].sum()

key1  key2
A     a        3
      b        3
B     a        4
      b       11
Name: data1, dtype: int64

In [71]:
df.groupby(["key1", "key2"])["data1"].sum().unstack()

key2  a   b
key1
A     3   3
B     4  11

In [72]:
df.pivot_table(values="data1", index="key1", columns="key2")

key2    a    b
key1
A     1.5  3.0
B     4.0  5.5

In [73]:
df.pivot_table(values="data1", index="key1", columns="key2").stack()

key1  key2
A     a       1.5
      b       3.0
B     a       4.0
      b       5.5
dtype: float64

In [74]:
df.pivot_table(values=["data1", "data1"], index="key1", columns="key2")

     data1      data2
key2     a    b     a     b
key1
A      1.5  3.0  11.5  13.0
B      4.0  5.5  14.0  15.5

In [75]:
df.pivot_table(values=["data1", "data1"], index="key1", columns="key2").stack()

           data1  data2
key1 key2
A    a       1.5   11.5
     b       3.0   13.0
B    a       4.0   14.0
     b       5.5   15.5

In [76]:
df.pivot_table(values=["data1", "data1"], index=["key1", "key2"])

           data1  data2
key1 key2
A    a       1.5   11.5
     b       3.0   13.0
B    a       4.0   14.0
     b       5.5   15.5

In [77]:
df.pivot_table(values=["data1", "data1"], columns=["key1", "key2"])

key1      A           B
key2      a     b     a     b
data1   1.5   3.0   4.0   5.5
data2  11.5  13.0  14.0  15.5

In [78]:
df.pivot_table(values=["data1", "data1"], columns=["key1", "key2"]).T

           data1  data2
key1 key2
A    a       1.5   11.5
     b       3.0   13.0
B    a       4.0   14.0
     b       5.5   15.5

Phương thức `pivot_table` có nhiều lựa chọn khác nhau cho các tham số, tham khảo: [`pandas.pivot_table`](https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html).

In [79]:
df

  key1 key2  data1  data2
0    A    a      1     11
1    A    a      2     12
2    A    b      3     13
3    B    a      4     14
4    B    b      5     15
5    B    b      6     16

In [80]:
df.pivot_table(index="key1", columns="key2", aggfunc=["sum", "max"])

       sum                 max
     data1     data2     data1    data2
key2     a   b     a   b     a  b     a   b
key1
A        3   3    23  13     2  3    12  13
B        4  11    14  31     4  6    14  16

In [81]:
df.pivot_table(index="key1", columns="key2", aggfunc={"data1": "sum", "data2": "max"})

     data1     data2
key2     a   b     a   b
key1
A        3   3    12  13
B        4  11    14  16

**Bài tập** Trên bảng dữ liệu `Iris Data Set`, dùng pivot table để tính trung bình (mean) và độ lệch chuẩn (std) của từng đặc trưng (sepal length, sepal width, petal length, petal width) trên từng nhóm hoa phân theo nhãn lớp (class).

In [82]:
# TODO